// const express=require("express")//3........
// const router=express.Router()//4.......
// router.get('/',function(req,res)
// {
//     res.write("working")
//     res.end("ending")
// })
// module.exports=router//5...............

const express=require("express")//3........
//const { indexing } = require("../controller")
const router=express.Router()//4.......
const controller=require("../controller")
router.get('/sendfile',controller.sendingfile)
router.get('/',controller.indexing)
router.post('/',controller.postmessage)
module.exports=router//5...............